[View in Colaboratory](https://colab.research.google.com/github/krapshsa/tensorflow-practice/blob/master/examples/shape.ipynb)

In [0]:
import tensorflow as tf

sess = tf.Session()

In [46]:
tensor1 = tf.constant(
    [
        [1., 1., 1.],
        [1., 1., 1.]
    ]
)

result1 = sess.run(tensor1)
print(result1)
print(tensor1.get_shape())
print(tf.shape(result1))
print(sess.run(tf.shape(result1)))

[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)
Tensor("Shape_58:0", shape=(2,), dtype=int32)
[2 3]


In [47]:
tensor2 = tf.constant(
    [
        [1., 1.],
        [1., 1.],
        [1., 1.]
    ]
)
result2 = sess.run(tensor2)
print(result2)
print(tf.shape(result2))
print(tensor2.get_shape())
print(sess.run(tf.shape(result2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
Tensor("Shape_60:0", shape=(2,), dtype=int32)
(3, 2)
[3 2]
